name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: [lint]
    strategy:
      matrix:
        version: [18, 22]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Install deps
        run: npm ci
      - name: Test unit
        run: npm run test:unit
      - name: Test e2e
        run: npm run test:e2e